### ISSUE TITLE
Feature request: Reduce the update rate

### ISSUE THREAD

**Issue by timbms** [RastislavMirek/FlexColorPicker#11]
It would be cool if the rate of the published updates was configurable

**Comment by RastislavMirek** [comment]
What do you mean by "published updates" ?

**Comment by timbms** [comment]
I am using colorPicker(:selectedColor) and colorPicker(:confirmedColor) 
and would like to call less frequently sendColorUpdate. In order to avoid flooding this interface
```
extension ColorPickerViewController: ColorPickerDelegate {
    func colorPicker(_ colorPicker: ColorPickerController, selectedColor: UIColor, usingControl: ColorControl) {
        sendColorUpdate(color: selectedColor)
    }

    func colorPicker(_ colorPicker: ColorPickerController, confirmedColor: UIColor, usingControl: ColorControl) {
        sendColorUpdate(color: confirmedColor)
    }
}
```

**Comment by RastislavMirek** [comment]
`ColorPickerDelegate` is called every time a user makes an interaction (moves finger on control etc.). This is standard behaviour user also by Cocoa Touch controls like `UISlider`. If you need to trottle user interaction you should do it on your end, in the class that implements `ColorPickerDelegate`.

**Comment by RastislavMirek** [comment]
Also note that `ColorPickerDelegate` is ment for eobserving color updates as they are happening. If you only need the final selected color, you can read the value (property `selectedColor` of `ColorPickerController` or `DefaultColorPickerViewController`) when user leaves the screen, presses confirm button or similar.

**Comment by timbms** [comment]
Got it working with your advice on ColorPickerDelegate. I have a throttler now
