### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by timbms** [RastislavMirek/FlexColorPicker#12]
Would be great to have Swift Package Manager support

**Comment by RastislavMirek** [comment]
Sure, no experience with that though. Whould you mind sending a pull request?

**Comment by RastislavMirek** [comment]
SPM support added as of version 1.3

**Comment by timbms** [comment]
I would have expected a Package.swift in root for an integration with Xcode

**Comment by RastislavMirek** [comment]
> I would have expected a Package.swift in root for an integration with Xcode

Thank you for comming back to this. As I am not using SPM myself all I did was merging pull request that claimed to add SPM support. If that is not the case, would you mind to send pull request yourself?

**Comment by timbms** [comment]
Attached is a proposal for Package.swift as GitHub was not allowing me to create a PR.
Put the manifest file Package.swift in the root directory of your repository. 
You will also need to tag the releases according to semantic versioning principles:
Tag for current version should be 1.3.0. Also, all future release will need to follow this principles

```
// swift-tools-version:5.1
//
//  Package.swift
//
//  Created by Tim Müller-Seydlitz on 30.09.19.
//

import PackageDescription

let package = Package(
    name: "FlexColorPicker",
    products: [
        .library(name: "FlexColorPicker", targets: ["FlexColorPicker"]),
    ],
    dependencies: [],
    targets: [
        .target(name: "FlexColorPicker",
                dependencies: [],
                path: "FlexColorPicker/Classes")
    ]
)
```

**Comment by RastislavMirek** [comment]
Added `Package.swift` as suggested by timbs. Please let me know if there are any further issues

**Comment by timbms** [comment]
I just upgraded to Catalina and latest Xcode 11.1. Now, while still using cocoa pod I see compiler errors like

>  'leftAnchor' is only available in iOS 9.0 or newer

though the target ist set to iOS 11.1. To be tried whether this can be solved by adding this snippet to Package.swift: 

> platforms: [
>         .iOS(.v9),
>   ],

Interestingly the compiler error doest not block the build. 
When I load the framework with SPM, the build fails and I see many more errors:

> Use of undeclared type 'UIGestureRecognizer'

I suppose that import statements needs to be made explicit for instance in ColorControlContentView.swift,...

**Comment by RastislavMirek** [comment]
Tim, you are helping me a lot with this. I feel that having working support for SPM might take 2-3 more minor versions... But we will get there before this week is over.

This is rather strange behaviour (when installed via cocoapods) but that's not the first time XCode is buggy.

I will add explicit imports and platform to `Package.swift` in 1.3.1 (to be released soon, also via cocoapods).

**Comment by RastislavMirek** [comment]
Ok, please try it now.
