### ISSUE TITLE
Tagging the release to make it available

### ISSUE THREAD

**Issue by timbms** [RastislavMirek/FlexColorPicker#17]
The release 1.3 is not accessible via Xcode SPM integration. Probably because the release is not tagged.

**Comment by RastislavMirek** [comment]
fixed in 1.3.1 please try it and let me know if it works.

**Comment by Chrichton** [comment]
Hi Rastislav.

Version 1.3.1 is not visible. Did you release it?

**Comment by RastislavMirek** [comment]
Yes, sure, just a few minutes ago. Can you try again?

**Comment by RastislavMirek** [comment]
Wait, tag was not pushed, let me fix that

**Comment by timbms** [comment]
Still can’t see the tagged release 1.3.1 on github.com

**Comment by RastislavMirek** [comment]
Now you should see it, let me know whether it compiles
