### ISSUE TITLE
Position of little circle on color pallet.

### ISSUE THREAD

**Issue by Knkush** [RastislavMirek/FlexColorPicker#19]
can't change position of little circle. its default 0 but I want set position to 180

**Comment by RastislavMirek** [comment]
You can set the color programatically and that will set the slider position to corresponding color. Changing just the slider position would make no sense.

**Comment by Knkush** [comment]
Thank you. and tell me please how I can change the color pallet and width of color in slider

**Comment by RastislavMirek** [comment]
First, read the documentation carefully. You are probably using default `DefaultColorPickerViewController` and with that you can only change the palette to rectangular using `useRadialPalette` property. If you want to change width of sliders, you cannot use `DefaultColorPickerViewController` but either `CustomColorPickerViewController` or `ColorPickerController`. See [this section of readme](https://github.com/RastislavMirek/FlexColorPicker#customisation) for quick start.
