### ISSUE TITLE
iOS 13 dark mode support

### ISSUE THREAD

**Issue by JaydenIrwin** [RastislavMirek/FlexColorPicker#25]
I noticed that the default background color of the view controllers is "white" and not "systemBackground"

**Comment by RastislavMirek** [comment]
Great point, thanks! Will fix that.

Best regards,

Rastislav Mirek
TypeSoft s. r. o.
rmirek@easytype.info <mailto:rmirek@easytype.info>
+420 774 316 244

**Comment by RastislavMirek** [comment]
Fixed in 1.4
