### ISSUE TITLE
Swift 5.2 complaint

### ISSUE THREAD

**Issue by timbms** [RastislavMirek/FlexColorPicker#26]
### Description:
* Have no warning when compiling

* Actual behaviour:
Swift 5.2 included in Xcode Version 11.4 reports a warning:
In UIImageExtension.swift
       `         let imageRect = CGRect(origin: .zero, size: size)`
> Initialization of immutable value 'imageRect' was never used; consider replacing with assignment to '_' or removing it
* FlexColorPicker version: 1.3.1
* Xcode version: Version 11.4.1

### How to reproduce:
Integrate project

**Comment by RastislavMirek** [comment]
Fixed in 1.3.2. Please note that this release will not be available via CocoaPods only via SPM and direct download.
