### ISSUE TITLE
1.4.1 Won't Run

### ISSUE THREAD

**Issue by JaydenIrwin** [RastislavMirek/FlexColorPicker#27]
<img width="340" alt="Screen Shot 2020-05-04 at 20 34 40" src="https://user-images.githubusercontent.com/13500479/81026045-c9a35180-8e46-11ea-8c38-e4e954396e51.png">

**Comment by RastislavMirek** [comment]
Thank you for report. What installation method did you use? Cocoapods, SPM or direct?

**Comment by JaydenIrwin** [comment]
SPM

**Comment by RastislavMirek** [comment]
Fixed in 1.4.2, released NOW. Please update and let me know if it works.

**Comment by JaydenIrwin** [comment]
Works, thanks!
