### ISSUE TITLE
Error when run it in xcode 10.1

### ISSUE THREAD

**Issue by jaydeeprudani** [RastislavMirek/FlexColorPicker#3]
![screenshot 2019-01-29 at 5 18 02 pm](https://user-images.githubusercontent.com/39905959/51906358-fff35500-23e9-11e9-8ae6-2bd7029d40a7.png)
This issue is occurs when i am running the demo code in xcode 10.1

Please give me solution on urgent base so i can use it.

Thanks

**Comment by RastislavMirek** [comment]
Hi jaydeeprudani, how did you install? Via CocoaPods or via direct installation? If you used Cocoapods, please try to install again - I just merged a pull request today that could might have resolved this issue.

Let me know whether it worked or not.

**Comment by blacklime** [comment]
Same issue here, installed via CocoaPods

**Comment by workingDog** [comment]
Same issue when I compile, installed via CocoaPods.
Did not find 2 plist files in pod.
Where exactly are the 2 plist files supposed to be?

**Comment by nagarajavrao** [comment]
Same issue here. Please update & push the code

**Comment by RastislavMirek** [comment]
Guys thank you for feedback. I tried to fix this 2 times already but still strugling... Anybody willing to help?

**Comment by bawarkamalqader** [comment]
I was able to find the solution, it is not a big issue, all you have to do is , select the Pods project, then the FlexColorPicker target, then, Build Phases, then Compile Sources, after expanding Compile Sources , remove the info.plist in the list, then all errors should resolve, i think @RastislavMirek  should do this and push it

![Screen Shot 2019-03-11 at 1 23 52 PM](https://user-images.githubusercontent.com/35786269/54116966-e853b700-4400-11e9-8ec4-4ddce3d0ee9e.png)

**Comment by RastislavMirek** [comment]
Closing as it is fixed for XCode 10.2 and FlexColorPicker 1.2.1.
