### ISSUE TITLE
Put examples how to work with custom view via code.

### ISSUE THREAD

**Issue by JLightMedia** [RastislavMirek/FlexColorPicker#30]
Hi. Your library is so cool but the big issue that absolutely not clear to understand how use it in code. Can you add code examples how add custom elements on the layout via code. Pls don't link your Demo project, it's a lot of code, that not easy to read.

**Comment by RastislavMirek** [comment]
Sorry, but I believe that the demo is as concise as it gets. If you are not willing to invest 30 minutes into going trough the Demo project than I cannot help you to make it any faster anyway.

However, I will give some guidance - read the appropriate section in the README and when studing the demo only focus on e.g. PickerInTabelDemoController. All the magic happens in the storyboard in the demo but all can be done with code as well. 

Another approach would be to read the in-code documentation starting from `ColorPickerController `. Basically, all you need to do is to add controls to its `colorControls` property and then lay them out on the screen using autolayout.

Btw. I am planning on improving the documentation on custom color pickers but I might only get to it in September.

**Comment by JLightMedia** [comment]
Thanks for answer! You'r absolutely right. Actually I've figured out how to implement ColorPicker in Storyboard  by your demo project. But unfortunately i didn't understand how to implement extra properties for the custom view by code. Anyway thank you for that.
Btw. I think some think wrong with my demo project. I have some error with debug file. 
<img width="1235" alt="Screenshot 2020-08-02 at 13 50 44" src="https://user-images.githubusercontent.com/27919923/89121459-bba5b100-d4c7-11ea-9a2f-32b40e627676.png">

And also one ViewController lost RadialHueControl. I just download demo project and run. Do I need to do some think else?
<img width="191" alt="Screenshot 2020-08-02 at 13 51 24" src="https://user-images.githubusercontent.com/27919923/89121460-c102fb80-d4c7-11ea-9f88-9fbb5463a71f.png">

And one extra question. 
In CustomColorPickerViewController.swift file in function viewDidLoad() I tried to change UI background color. But after some tests my changes not affect on UI. It's always .systemBackground Is it right place for change that parameter? I understand, that viewDidLoad() never called even CustomView appear on the screen.

**Comment by JLightMedia** [comment]
Hi. I've founded some answer on my questions. May be for someone it will be useful.

1. viewDidLoad() I understood why this method have not worked. I don't know why, but when I run project the builder compiles CustomColorPickerViewController.swift only once. After first run, builder don't recompile this file again, that's why when I added my parameters for customise ViewController, it didn't affect on final result. For use new change I have to Clear Build Folder (Shift+Cmd+K) and Run compiler again. After that new changes affect on the project.

2. I didn't mention about that issue, but I think maybe it will be useful. When I use  DefaultColorPicker I could set "Selected Color", before open ViewController in this way:

```
        if let destinationColorPicker = segue.destination as? ColorPickerControllerProtocol {
            destinationColorPicker.delegate = self
            destinationColorPicker.selectedColor = UIColor.systemPink
            }
```

But it does not work with CustomColorPicker. For do that i had to create Segue and instance of CustomColorPicker class. I don't know whether my method is elegant but it works. Maybe @RastislavMirek could tell, what the best way to do that.

```
 override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        print("Prepare seque color picker")
        if let destinationColorPicker = segue.destination as? ColorPickerControllerProtocol {
            destinationColorPicker.delegate = self
            }
        
        if segue.identifier == "PresentColorPicker" {
            let destVC = segue.destination as! CustomColorPickerViewController
            destVC.selectedColor = sender as? UIColor ?? .white
            }
    }
```

**Comment by JLightMedia** [comment]
And also, sometimes one issue appear when I try run project. What does it mean?
<img width="328" alt="Screenshot 2020-08-11 at 17 57 40" src="https://user-images.githubusercontent.com/27919923/89916455-4725ed00-dc00-11ea-9ba8-9214b0365244.png">
