### ISSUE TITLE
ColorPickerDelegate

### ISSUE THREAD

**Issue by ShubhamIos16** [RastislavMirek/FlexColorPicker#32]
func colorPicker(_: ColorPickerController, confirmedColor: UIColor, usingControl: ColorControl) {
 }

This Delegate Method will not call Please suggest me..

**Comment by RastislavMirek** [comment]
That is only called when user taps the preview control to confirm the color choice. You probably want to use the other delegate method to keep track of changes as they are happening. read in code documentation of the delegate and its methods for details.

**Comment by ShubhamIos16** [comment]
Hi,
Actually i want the color when i am complete the selection. Only last selcted color i want
