### ISSUE TITLE
AutoLayout With ScrollView Crashing - iOS 15 Xcode 13

### ISSUE THREAD

**Issue by gintechsystems** [RastislavMirek/FlexColorPicker#35]
Hello,

It seems to crash no matter what constraints I set when adding the control to a scrollview that has auto layout.

Any suggestions? I will update this post with the crash stacktrace and a screenshot of my constraints.

Thanks
Joe

**Comment by RastislavMirek** [comment]
Can you provide more details, please? Exception with stack trace and code sample?

Thank you

**Comment by RastislavMirek** [comment]
This should be fixed in 1.4.4
