### ISSUE TITLE
Can I have my custom colors in circle palette.  

### ISSUE THREAD

**Issue by skv6631** [RastislavMirek/FlexColorPicker#43]
Hi, I don't want all those VIBGYOR colors in my color picker, I need only 3 colors that can spread in a circle. Can this be achievable.

**Comment by RastislavMirek** [comment]
Yes, you can create your own "picker" component with just 3 colors. How to do it is in readme. Hope this helps.

**Comment by skv6631** [comment]
@RastislavMirek Can you please let me know where I can change the color details. Am very new to this.
