### ISSUE TITLE
Upgrade to Swift 5.1

### ISSUE THREAD

**Issue by timbms** [RastislavMirek/FlexColorPicker#9]
An upgrade to latest Swift 5.1 would be great

**Comment by RastislavMirek** [comment]
Ok, ni problem I am on holyday right now but will update once I am back.

**Comment by RastislavMirek** [comment]
Upgraded to Swift 5 as of version 1.3

**Comment by weakfl** [comment]
@RastislavMirek can you please push the latest release(s) to trunk? Pod is still on v1.2.1 on CocoaPods.
